name: Trigger clair db image build

# This workflow creates/reopens PR and closes it
# in order to trigger PAC to build clair DB image

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

permissions:
  contents: write

env:
  SOURCE_BRANCH: main # building from main

jobs:
  test:
    name: Build the new image
    runs-on: ubuntu-24.04

    steps:
    - name: Check out repository code
      uses: actions/checkout@v6
      with:
        ref: 'main'
    - name: create empty commit
      run: |
          git config --global user.email "<>"
          git config --global user.name "daily-build-trigger"
          echo "Creating empty commit."
            git commit --allow-empty -m "$(date)"
            git push origin "${SOURCE_BRANCH}" -f
